// app/layout.js 

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// htmlのテンプレートを表示するための関数コンポーネント
//
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
